Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  namespace :api do
    namespace :v1 do
      resources :xforms_xforms
      resources :xforms_person_repeat_attributes
      resources :xforms_medical_history_fields
      resources :visit_types
      resources :visit_attribute_types
      resources :visit_attributes
      resources :visits
      resources :users
      resources :user_roles
      resources :user_properties
      resources :tribes
      resources :test_orders
      resources :serialized_objects
      resources :scheduler_task_config_properties
      resources :scheduler_task_configs
      resources :room_temperatures
      resources :role_roles
      resources :role_privileges
      resources :roles
      resources :reporting_report_requests
      resources :reporting_report_design_resources
      resources :reporting_report_designs
      resources :report_schema_xmls
      resources :report_objects
      resources :relationship_types
      resources :relationships
      resources :provider_attribute_types
      resources :provider_attributes
      resources :providers
      resources :program_workflow_states
      resources :program_workflows
      resources :program_attribute_types
      resources :programs
      resources :privileges
      resources :person_names
      resources :person_merge_logs
      resources :person_attribute_types
      resources :person_attributes
      resources :person_addresses
      resources :people
      resources :patient_states
      resources :patient_program_attributes
      resources :patient_programs
      resources :patient_identifier_types
      resources :patient_identifiers
      resources :patients
      resources :orders
      resources :order_type_class_maps
      resources :order_types
      resources :order_set_members
      resources :order_sets
      resources :order_groups
      resources :order_frequencies
      resources :observations
      resources :notification_templates
      resources :notification_alert_recipients
      resources :notification_alerts
      resources :notes
      resources :metadatasharing_imported_package_items
      resources :metadatasharing_imported_packages
      resources :metadatasharing_imported_items
      resources :metadatasharing_exported_packages
      resources :logic_token_registration_tags
      resources :logic_token_registrations
      resources :logic_rule_token_tags
      resources :logic_rule_tokens
      resources :logic_rule_definitions
      resources :location_tag_maps
      resources :location_tags
      resources :location_attribute_types
      resources :location_attributes
      resources :locations
      resources :liquibasechangeloglocks
      resources :liquibasechangelogs
      resources :htmlformentry_html_forms
      resources :hl7_sources
      resources :hl7_in_queues
      resources :hl7_in_errors
      resources :hl7_in_archives
      resources :global_properties
      resources :formentry_xsns
      resources :formentry_queues
      resources :formentry_errors
      resources :formentry_archives
      resources :form_resources
      resources :form_fields
      resources :forms
      resources :field_types
      resources :field_answers
      resources :fields
      resources :encounter_types
      resources :encounter_roles
      resources :encounter_providers
      resources :encounter_diagnoses
      resources :encounters
      resources :drug_reference_maps
      resources :drug_orders
      resources :drug_ingredients
      resources :drugs
      resources :dataintegrity_integrity_checks
      resources :conditions
      resources :concept_words
      resources :concept_stop_words
      resources :concept_state_conversions
      resources :concept_set_deriveds
      resources :concept_sets
      resources :concept_reference_term_maps
      resources :concept_reference_terms
      resources :concept_reference_sources
      resources :concept_reference_maps
      resources :concept_proposal_tag_maps
      resources :concept_proposals
      resources :concept_numerics
      resources :concept_name_tag_maps
      resources :concept_name_tags
      resources :concept_names
      resources :concept_map_types
      resources :concept_descriptions
      resources :concept_datatypes
      resources :concept_complexes
      resources :concept_classes
      resources :concept_attribute_types
      resources :concept_attributes
      resources :concept_answers
      resources :concepts
      resources :cohort_members
      resources :cohorts
      resources :clob_datatype_storages
      resources :care_settings
      resources :allergy_reactions
      resources :allergies
      resources :auth do
        collection do
          post 'login'
        end
      end
    end
  end
end
