# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: emr_api_core_test
          MYSQL_ROOT_PASSWORD: change_password 
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      # DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Add or replace dependency steps here
      - name: Set up Ruby 3.1.2
        uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4 # v1.127.0
        with:
          ruby-version: 3.1.2
      # Install dependecies
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Verify MySQL connection from host
        run: |
          sudo apt-get install -y mysql-client libmysqlclient-dev
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -uroot -pchange_password -e "CREATE USER 'test_user'@'%' IDENTIFIED WITH mysql_native_password BY 'change_password'"
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -uroot -pchange_password -e "GRANT ALL PRIVILEGES ON *.* TO 'test_user'@'%' WITH GRANT OPTION"
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -uroot -pchange_password -e "FLUSH PRIVILEGES"
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -uroot -pchange_password -e "SELECT user,host FROM mysql.user"
      # Copy database config
      - name: Copy database configutation
        run: cp config/database.yml.example config/database.yml
      # Add or replace database setup steps here
      - name: Set up database schema
        env:
          RAILS_ENV: test
          DB_PORT: 3306
          CI: true
        run: |
          bundle exec rails db:prepare
      # Add or replace test runners here
      - name: Run tests
        env:
          RAILS_ENV: test
          DB_PORT: 3306
          CI: true
        run: bundle exec rails test